apiVersion: v1
kind: Service
metadata:
  name: gptshaik-frontend-service
  namespace: gptshaik
  labels:
    app: gptshaik
    tier: frontend
spec:
  type: NodePort
  selector:
    app: gptshaik
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
