apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaikgpt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shaikgpt-backend
  template:
    metadata:
      labels:
        app: shaikgpt-backend
    spec:
      containers:
      - name: backend
        image: shaikgpt-backend:latest   # Use your local image
        imagePullPolicy: IfNotPresent    # Don't try to pull from Docker Hub
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: shaikgpt-secrets
        
---
apiVersion: v1
kind: Service
metadata:
  name: shaikgpt-backend
spec:
  selector:
    app: shaikgpt-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP   # default, can change to NodePort if you want external access
