apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaikgpt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shaikgpt-frontend
  template:
    metadata:
      labels:
        app: shaikgpt-frontend
    spec:
      containers:
      - name: frontend
        image: shaikgpt-frontend:latest   # Use your local image
        imagePullPolicy: IfNotPresent     # Don't try to pull from Docker Hub
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shaikgpt-frontend
spec:
  selector:
    app: shaikgpt-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort   # allows access from browser via Minikube/Docker Desktop
